INSERT INTO `universities` (`name`, `abbr`, `region`, `city`) VALUES
('National Central University', 'NCU', 'Zhongli City', 'Taoyuan County'),
('National Cheng Kung University', 'NCKU', 'East District', 'Tainan'),
('National Chengchi University', 'NCCU', 'Wenshan District', 'Taipei'),
('National Chi Nan University', 'NCNU', 'Puli Township', 'Nantou County'),
('National Chiao Tung University', 'NCTU', 'East District', 'Hsinchu'),
('National Chiayi University', 'NCYU', 'East District', 'Chiayi'),
('National Chung Cheng University', 'CCU', 'Minxiong Township', 'Chiayi County'),
('National Chung Hsing University', 'NCHU', 'South District', 'Taichung'),
('National Dong Hwa University', 'NDHU', 'Shoufeng Township', 'Hualien County'),
('National Ilan University', 'NIU', 'Yilan City', 'Yilan County'),
('National Quemoy University', 'NQU', 'Jinning Township', 'Kinmen'),
('National Sun Yat-sen University', 'NSYSU', 'Gushan District', 'Kaohsiung'),
('National Taipei University', 'NTPU', 'Sanxia District', 'New Taipei'),
('National Taitung University', 'NTTU', 'Taitung City', 'Taitung County'),
('National Taiwan University', 'NTU', 'Daan District', 'Taipei'),
('National Taiwan Ocean University', 'NTOU', 'Zhongzheng District', 'Keelung'),
('National Tsing Hua University', 'NTHU', 'East District', 'Hsinchu'),
('National United University', 'NUU', 'Miaoli City', 'Miaoli County'),
('National University of Kaohsiung', 'NUK', 'Nanzi District', 'Kaohsiung'),
('National University of Tainan', 'NUTN', 'West Central District', 'Tainan'),
('National Yang Ming University', 'NYMU', 'Beitou District', 'Taipei');